CREATE DATABASE CLASE3;

USE CLASE3;

CREATE TABLE clientes(
	id_cliente INT NOT NULL, -- TIENE QUE EXISTIR UNO POR CADA CLIENTE, NO PUEDE FALTAR ESTE DATO --
	nombre VARCHAR(100) NOT NULL, --100 CARACTERES PARA UN NOMBRE ES MAS QUE SUFICIENTE --
	perfil_bio VARCHAR(500) NOT NULL, -- 500 CARACATERES PARA UNA BREVE BIOGRAFIA ES SUFICIENTE--
	fecha_registro DATE NOT NULL, --SE TRATA DE UNA FECHA--

);

CREATE TABLE productos(
	id_producto INT NOT NULL,-- TIENE QUE EXISTIR UNO POR CADA ´PRODUCTO, NO PUEDE FALTAR ESTE DATO --
	descripcion VARCHAR(255) NOT NULL,--255 CARACTERES PARA UN NOMBRE ES MAS QUE SUFICIENTE --
	precio DECIMAL(12,2) NOT NULL, --AL TRATARSE DE PRECIO ES NECESARIO QUE PUEDA TENER UN TIPO DE DATO DE NUMERO DECIMAL)
	esta_activo VARCHAR(2) NOT NULL, --PARA RESONDER "SI" O "NO"--

);